# Generated by Django 5.2.13 on 2026-04-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='diagnosis',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
