# Generated by Django 5.2.13 on 2026-04-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='ddress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
