# Generated by Django 5.2.13 on 2026-04-21 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_ddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='ddress',
            new_name='address',
        ),
    ]
