# Generated by ChatGPT on 2026-04-15

from django.db import migrations


def seed_core_symptoms(apps, schema_editor):
    Symptom = apps.get_model('symptoms', 'Symptom')

    core = [
        {'keyword': 'fever', 'name': 'Fever'},
        {'keyword': 'cough', 'name': 'Cough'},
        {'keyword': 'sore_throat', 'name': 'Sore throat'},
        {'keyword': 'headache', 'name': 'Headache'},
        {'keyword': 'weakness', 'name': 'Weakness'},
        {'keyword': 'runny_nose', 'name': 'Runny nose'},
        # missing in your DB but used by the app
        {'keyword': 'abdominal_pain', 'name': 'Abdominal pain'},
        {'keyword': 'allergy', 'name': 'Allergy'},
    ]

    for row in core:
        Symptom.objects.get_or_create(keyword=row['keyword'], defaults={'name': row['name']})


def unseed_core_symptoms(apps, schema_editor):
    Symptom = apps.get_model('symptoms', 'Symptom')
    Symptom.objects.filter(keyword__in=['abdominal_pain', 'allergy']).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('symptoms', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_core_symptoms, reverse_code=unseed_core_symptoms),
    ]

